
import java.awt.HeadlessException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author RJG-SERVER
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        txtNomyApe = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtLugNac = new javax.swing.JTextField();
        txtDom = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        cbxProvincia = new javax.swing.JComboBox<>();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFemenino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtDpto = new javax.swing.JTextField();
        cbxCarrera = new javax.swing.JComboBox<>();
        btnRegistro = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(852, 688));

        tituloPanel.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        tituloPanel.setText("Registro de Estudiante");

        txtNomyApe.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre y Apellido"));

        txtDni.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI(solo numeros)"));

        txtLugNac.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar de Nacimiento"));

        txtDom.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio Actual"));

        txtFechaNac.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Nacimiento"));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        txtAño.setBorder(javax.swing.BorderFactory.createTitledBorder("Año"));

        cbxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ...", "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucumán" }));
        cbxProvincia.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia"));

        grupoSexo.add(rbtMasculino);
        rbtMasculino.setText("Masculino");

        grupoSexo.add(rbtFemenino);
        rbtFemenino.setText("Femenino");

        jLabel1.setText("Sexo ");

        txtDpto.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamento"));

        cbxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ...", "Tec. Sup. en Economia Social", "Administracion Publica", "Comercio Internacional" }));
        cbxCarrera.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrera"));

        btnRegistro.setText("Registrar");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloPanel)
                .addGap(299, 299, 299))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCarrera, 0, 293, Short.MAX_VALUE)
                            .addComponent(cbxProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLugNac)
                            .addComponent(txtNomyApe)
                            .addComponent(txtDom))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtFechaNac)
                            .addComponent(txtDni)
                            .addComponent(txtDpto)
                            .addComponent(txtAño))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtMasculino)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addComponent(rbtFemenino)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tituloPanel)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomyApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLugNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtFemenino)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
       
               if (!txtNomyApe.getText().isEmpty() && !txtDni.getText().isEmpty()
                && !txtDom.getText().isEmpty() && !txtDpto.getText().isEmpty()
                && !txtFechaNac.getText().isEmpty() && !txtLugNac.getText().isEmpty()
                && !txtTelefono.getText().isEmpty() && !txtAño.getText().isEmpty()
                && !(cbxProvincia.getSelectedItem().toString().contentEquals("Seleccione ..."))
                && !(cbxCarrera.getSelectedItem().toString().contentEquals("Seleccione ..."))
                && ((rbtMasculino.isSelected()) || (rbtFemenino.isSelected()))) {

//                  JOptionPane.showMessageDialog(null, "paso la validacion");
            try {
                String nombre = txtNomyApe.getText();
                String dni = txtDni.getText();
                String domicilio = txtDom.getText();
                String fechaNac = txtFechaNac.getText();
                String lugarNac = txtLugNac.getText();
                String provincia = (String) cbxProvincia.getSelectedItem();
                String departamento = txtDpto.getText();
                String telefono = txtTelefono.getText();
                String carrera = (String) cbxCarrera.getSelectedItem();
                String año = txtAño.getText();
                String sexoselect = "_";

                if (rbtFemenino.isSelected()) {
                    sexoselect = "Femenino";
                } else {
                    if (rbtMasculino.isSelected()) {
                        sexoselect = "Masculino";
                    }
                }

                Estudiante estudiante = new Estudiante(carrera, año, 
                        nombre, dni, sexoselect, domicilio, provincia,
                        departamento, fechaNac, lugarNac, telefono);

                if (ControllerEstudiante.existeEstudiante(txtDni.getText()) == false) {

                    ControllerEstudiante.registrarEstduiante(estudiante);

                    JOptionPane.showMessageDialog(null, "Estudiante Agregado");

                    txtNomyApe.setText("");
                    txtDni.setText("");
                    txtDom.setText("");
                    txtFechaNac.setText("");
                    txtLugNac.setText("");
                    cbxProvincia.setSelectedIndex(0);
                    txtDpto.setText("");
                    grupoSexo.clearSelection();
                    txtTelefono.setText("");
                    cbxCarrera.setSelectedIndex(0);
                    txtAño.setText("");

                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe un estudiante con ese DNI");
                }
            } catch (NumberFormatException | HeadlessException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }

        
    }//GEN-LAST:event_btnRegistroActionPerformed

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    
    public JComboBox<String> getCbxCarrera() {
        return cbxCarrera;
    }

    public void setCbxCarrera(JComboBox<String> cbxCarrera) {
        this.cbxCarrera = cbxCarrera;
    }

    public JComboBox<String> getCbxProvincia() {
        return cbxProvincia;
    }

    public void setCbxProvincia(JComboBox<String> cbxProvincia) {
        this.cbxProvincia = cbxProvincia;
    }

    public JRadioButton getRbtFemenino() {
        return rbtFemenino;
    }

    public void setRbtFemenino(JRadioButton rbtFemenino) {
        this.rbtFemenino = rbtFemenino;
    }

    public JRadioButton getRbtMasculino() {
        return rbtMasculino;
    }

    public void setRbtMasculino(JRadioButton rbtMasculino) {
        this.rbtMasculino = rbtMasculino;
    }

    public JTextField getTxtAño() {
        return txtAño;
    }

    public void setTxtAño(JTextField txtAño) {
        this.txtAño = txtAño;
    }

    public JTextField getTxtDni() {
        return txtDni;
    }

    public void setTxtDni(JTextField txtDni) {
        this.txtDni = txtDni;
    }

    public JTextField getTxtDom() {
        return txtDom;
    }

    public void setTxtDom(JTextField txtDom) {
        this.txtDom = txtDom;
    }

    public JTextField getTxtDpto() {
        return txtDpto;
    }

    public void setTxtDpto(JTextField txtDpto) {
        this.txtDpto = txtDpto;
    }

    public JTextField getTxtFechaNac() {
        return txtFechaNac;
    }

    public void setTxtFechaNac(JTextField txtFechaNac) {
        this.txtFechaNac = txtFechaNac;
    }

    public JTextField getTxtLugNac() {
        return txtLugNac;
    }

    public void setTxtLugNac(JTextField txtLugNac) {
        this.txtLugNac = txtLugNac;
    }

    public JTextField getTxtNomyApe() {
        return txtNomyApe;
    }

    public void setTxtNomyApe(JTextField txtNomyApe) {
        this.txtNomyApe = txtNomyApe;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> cbxCarrera;
    private javax.swing.JComboBox<String> cbxProvincia;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDom;
    private javax.swing.JTextField txtDpto;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtLugNac;
    private javax.swing.JTextField txtNomyApe;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
